apiVersion: 1
datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: influxdb
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: ${INFLUXDB_DB_NAME}
    #user: my_user
    #password: my_password
    jsonData:
      httpMode: POST
      version: InfluxQL
    editable: true
