apiVersion: 1
datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    #uid: prometheus_uid

  - name: influxdb
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: ${INFLUXDB_DB_NAME}
    jsonData:
      httpMode: POST
      version: InfluxQL
    editable: true
    uid: P3C6603E967DC8568
