{
 "title": "Container Health",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Active Processes / Thread Count",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Zookeeper Thread Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_pids{job=\"docker_stats\", name=\"zookeeper\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Broker Thread Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_pids{job=\"docker_stats\", name=\"broker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Centos Thread Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_pids{job=\"docker_stats\", name=\"centos\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka-UI Thread Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_pids{job=\"docker_stats\", name=\"kafka-ui\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafana Thread Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_pids{job=\"docker_stats\", name=\"grafana\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prometheus Thread Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_pids{job=\"docker_stats\", name=\"prometheus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Producere Thread Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_pids{job=\"docker_stats\", name=\"producer\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Producer Thread Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_pids{job=\"docker_stats\", name=\"error-producer\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Influx DB Thread Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_pids{job=\"docker_stats\", name=\"influxdb\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer Thread Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_pids{job=\"docker_stats\", name=\"consumer\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Opensearch Thread Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_pids{job=\"docker_stats\", name=\"opensearch\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Opensearch Dashboards Thread Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_pids{job=\"docker_stats\", name=\"opensearch-dashboards\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logstash Thread Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_pids{job=\"docker_stats\", name=\"logstash\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Filebeat Thread Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_pids{job=\"docker_stats\", name=\"filebeat\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CPU / MEMORY Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Container CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "container_cpu_usage{job=\"docker_stats\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "container_memory_percent{job=\"docker_stats\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container CPU Usage",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_cpu_usage{job=\"docker_stats\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_percent{job=\"docker_stats\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "NETWORK I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Network Input",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "container_net_io_rx{job=\"docker_stats\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network Output",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "expr": "container_net_io_tx{job=\"docker_stats\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "BLOCK I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Block I/O Read",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "container_block_io_read{job=\"docker_stats\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Block I/O Write",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "targets": [
    {
     "expr": "container_block_io_write{job=\"docker_stats\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}