{
 "title": "New dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "Currency Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TRY",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fixer_table",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "currency::tag", "operator": "=", "value": "TRY" }
     ]
    }
   ]
  },
  {
   "title": "EUR",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fixer_table",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "currency::tag", "operator": "=", "value": "EUR" }
     ]
    }
   ]
  },
  {
   "title": "USD",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fixer_table",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "currency::tag", "operator": "=", "value": "USD" }
     ]
    }
   ]
  },
  {
   "title": "BTC",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fixer_table",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "currency::tag", "operator": "=", "value": "BTC" }
     ]
    }
   ]
  },
  {
   "title": "Currency Values by Time",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "currency::tag" ], "type": "tag" }
     ],
     "measurement": "fixer_table",
     "query": "SELECT \"rate\" FROM \"fixer_table\" WHERE $timeFilter GROUP BY \"currency\"::tag",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Kafka Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Message Count by Partition",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "kafka_topic_partition_current_offset{instance=\"centos:9308\", topic=\"fixer-incoming\"}",
     "legendFormat": "Partition #{{partition}}"
    }
   ]
  },
  {
   "title": "Message Count by Partition",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 12, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_topic_partition_current_offset{instance=\"centos:9308\", topic=\"fixer-incoming\"}",
     "legendFormat": "Partition #{{partition}}"
    }
   ]
  },
  {
   "title": "Active Broker Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_brokers{instance=\"centos:9308\"}",
     "legendFormat": "Cluster #1"
    }
   ]
  }
 ]
}