# This file is where you define your pipelines. You can define multiple.
# For more information on multiple pipelines, see the documentation:
#   https://www.elastic.co/guide/en/logstash/current/multiple-pipelines.html

#- pipeline.id: main
#  path.config: "/usr/share/logstash/pipeline"

- pipeline.id: broker
  path.config: "/usr/share/logstash/config/logstash-broker.conf"

- pipeline.id: zookeeper
  path.config: "/usr/share/logstash/config/logstash-zookeeper.conf"

- pipeline.id: producer
  path.config: "/usr/share/logstash/config/logstash-producer.conf"

- pipeline.id: filebeat
  path.config: "/usr/share/logstash/config/logstash-filebeat.conf"

- pipeline.id: kafka
  path.config: "/usr/share/logstash/config/logstash-kafka.conf"
